name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */12 * * *' # Runs automatically every 12 hours

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the bot to push to your repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Empty Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git commit --allow-empty -m "Keep-alive: Resetting Streamlit sleep timer"
          git push
